### ISSUE TITLE
Adding skills to an existing plan

### ISSUE THREAD

**Issue by ilovepuppers** [ddavaham/levelv#6]
Adding a skill to an existing plan [Select skill, choose level, submit] results in `Whoops, looks like something went wrong.`

Upon refreshing the skill plan sometimes the new skill is present, sometimes it is at the wrong level.

**Comment by ddavaham** [comment]
Can u give an example?

**Comment by ilovepuppers** [comment]
I navigate from the Dashboard > skill plan manager > my plan.

In this example I add Command Ships 5 (1-4 are already in the plan).  I get an error page under the url `https://levelv.space/skillplan/d6d374a70d3969e94a67a3ee1096194c`

However on returning to the plan command ships 5 is now included

**Comment by ddavaham** [comment]
Yup,

Found this little bug earlier today. It is patched locally. I'll see if I
can deploy later tonight

Thank you

**Comment by ilovepuppers** [comment]
In fact, any journey that submits a change to the plan results in the same error page

**Comment by ddavaham** [comment]
This should've been resolved with dfd18981c31b1737077b41ac21664c2dac0b67f. Let me know if it is still an issue.
