### ISSUE TITLE
Minimum Required Skill

### ISSUE THREAD

**Issue by Silight** [ddavaham/levelv#8]
I would like to be able to work backwards. Can we use the minimum requirements for particular items to create a skill plan? 

For example, if I want to fly a Stratios, the minimum skills required would be: 
Spaceship Command II
Amarr Frigate III
Amarr Destroyer III
Amarr Cruiser II
Gallente Frigate III
Gallente Destroyer III
Gallente Cruiser II

So, I select Stratios and the minimum skills import to a skill plan.

**Comment by ddavaham** [comment]
You should already be able to do this. The wording on the UI has not been pushed yet, but the functionality on the backend has been updated to handle searching for Ships, Modules, and Skills themselves

**Comment by Silight** [comment]
Okay, I see it now. I think it just wasn't letting me do it because of the other issue. Thank you! I am loving the site and really appreciate your work.

**Comment by ddavaham** [comment]
I pushed some changes just now. Please remember the site, and furthermore that module, is still under heavy development, hence no public announcement yet. You can easily reach me here by reporting an issue or joining me on [Discord](https://discord.gg/7sBeach).
